# -*- coding: utf-8 -*-
"""task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3XVjRheKr2x09w08kdutguZAJ5sLrUR
"""

import random


user_choice = input("Enter your choice (rock, paper, scissors): ").lower()

computer_choice = random.choice(['rock', 'paper', 'scissors'])


if user_choice == computer_choice:
    result = "It's a tie!"
elif user_choice == 'rock' and computer_choice == 'scissors':
    result = "You win!"
elif user_choice == 'paper' and computer_choice == 'rock':
    result = "You win!"
elif user_choice == 'scissors' and computer_choice == 'paper':
    result = "You win!"
else:
    result = "Computer wins!"

print(f"You chose: {user_choice}")
print(f"Computer chose: {computer_choice}")
print(result)